name: CI Build and Artifact Upload

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package
      

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tictactoe
        path: ./tic-tac-toe-1.0.jar
